modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [200]  # You can add other success codes if needed
      method: GET
      headers:
        Host: 10.0.0.4

  tcp_mysql:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
      - expect: "^.*$"
      tls: false
      preferred_ip_protocol: "ip4"
