# File: playbook.yml

- name: Clonage du dépôt et Installation des dépendances pour le grafana
  hosts: grafana_server
  tasks:
    - name: Clonage du dépôt grafana
      git:
        repo: "http://oauth2:glpat-JrBv41eTKELFtPhL15Lu@192.168.5.35/nsa_810/prometheus-grafana.git"
        dest: /home/service-web/grafana
      become_user: service-web
      tags:
        - build

    - name: build docker
      command: docker compose build
      args:
        chdir: /home/service-web/grafana/
      become_user: service-web
      tags:
        - build

    - name: lancer docker
      command: docker compose up -d 
      args:
        chdir: /home/service-web/grafana/
      become_user: service-web
      tags:
        - deploy


