global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'sys-info-front'
    static_configs:
      - targets: ['192.168.5.32:9100']

  - job_name: 'sys-info-back'
    static_configs:
      - targets: ['192.168.5.33:9100']

  - job_name: 'sys-info-gitlab'
    static_configs:
      - targets: ['192.168.5.35:9100']

  - job_name: 'sys-info-october'
    static_configs:
      - targets: ['192.168.5.34:9100']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  
    static_configs:
      - targets:
          - http://10.0.0.4  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
  - "alert.rules.yml"
