version: '3.8'
services:
  db: # the service hosting your MySQL instance
    image: mysql:5.7 # the image and tag docker will pull from docker hub
    container_name: dev_db
    volumes: # this section allows you to configure persistence within multiple restarts
      - db_data:/var/lib/mysql
    restart: always # if the db crash somehow, restart it
    environment: # env variables, you usually set this to override existing ones
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - backend

  api:
    container_name: dev_api
    image: sample-express-app
    build: .
    restart: always
    environment:
      DB_HOST: db
    ports:
      - "3001:3000"
    networks:
      - backend
    depends_on: # set a dependency between your service and the database: this means that your application will not run if the db service is not running, but it doesn't assure you that the dabase will be ready to accept incoming connection (so your application could crash untill the db initializes itself)
      - db
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /home/admuser/front/config.yml:/etc/promtail/config.yml  # Adjusted to match the file path used in command
    command: -config.file=/etc/promtail/config.yml

networks:
  backend:
    driver: bridge
volumes:
  db_data: