version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: octobercms_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: octobercms_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: octobercms
      MYSQL_USER: octobercms_user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
